### ISSUE TITLE
New LeapfrogUI has Feature Parity with Chatbot UI

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai-sdk#200]
- [x] Prompt Selection
- [x] Persist Conversations
- [x] Search
- [x] Hide plugin keys button
- [x] Color Palette
- [x] Persona Selection

## Notes:
* https://carbondesignsystem.com/

**Comment by CollectiveUnicorn** [comment]
Need to support rendering markdown in the output.

**Comment by CollectiveUnicorn** [comment]
Added optional RAG support with the chroma server
